Adding Basic Implementation Of Graph
rohan472000/Java-DSA-InterviewPrep pull request #85
Opened 2023-10-04 15:26 UTC by shivamk23

## Pull Request Checkboxes and descriptions

### Description
This is a basic representation of Graphs , and you can extend it Based on your requirements. You might want to create separate classes for vertices and edges, implement a direct graph, or add additional functionality such as depth-first search or breadth-first-search.

### Related/Fixes Issue
 Issue : #67

### Changes Made
I have added a basic implementation of graph which any beginner can easily able to understand.

1. The add Edge method is used to add an undirected edge between two vertices.
2. The print Graph method uses a lambda expression for concise printing.
3. The Main class creates an instance of the Graph class and adds edges to it.

2023-10-04 17:32 UTC, rohan472000 commented
Add description and Wikipedia links under comments in.java files

2023-10-04 19:15 UTC, shivamk23 commented
okay sure @rohan472000

2023-10-04 19:24 UTC, shivamk23 commented
Done @rohan472000, now please merge my commit.

2023-10-05 03:07 UTC, rohan472000 requested changes
Keep those description and link at top now in middle.

2023-10-05 06:10 UTC, shivamk23 commented
Added description and link at top. @rohan472000

2023-10-05 07:25 UTC, rohan472000 commented
You have proposed two .java files of graph...whats the difference in them?

2023-10-05 14:01 UTC, rohan472000 commented
> Sorry @rohan472000 it's my mistake, can you please merge my code. if everything is alright.

why so desperate to get your code merged?? after review and correction it will be merged.

2023-10-05 14:02 UTC, rohan472000 approved these changes

2023-10-05 14:02 UTC, rohan472000 commented on Graphs/ImplementingGraphs.java
> +   3. Print the graph's adjacency list using the printGraph method.
```suggestion
```

2023-10-05 14:04 UTC, merged